name: Build Release (NPM & JSR) (On Release)

on:
  release:
    types:
      - published

jobs:
  release:
    name: Build Release (NPM & JSR) (On Release)
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Set version # Get the version from the release tag and update in [config].json
        uses: maks11060/deno-publish-version@v2

      - name: Publish to JSR
        run: deno publish --allow-dirty

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"

      - name: Run Deno dnt
        run: deno task npm ${{ github.ref_name }}

      - name: Check Version
        run: cat ./npm/package.json | jq .version

      - name: Publish to NPM
        run: cd ./npm && yarn publish --verbose --access public --new-version ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
