name: Update API (On Demand)
on:
  workflow_dispatch:

jobs:
  update-providers:
    name: Update API (On Demand)
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Update dependencies
        run: deno add npm:openapi-fetch

      - name: Fetch & Update OpenAPI Types
        run: deno task update

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update API (on demand)
          commit_options: "--no-verify"

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes detected"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes detected"

      - name: "Create Release"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: ""
